server {
    listen       80;
    server_name  localhost;

    # 开启 Gzip 压缩，加快大屏 JS 资源加载速度
    gzip on;
    gzip_min_length 1k;
    gzip_comp_level 6;
    gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 最关键的一句：支持 Vue Router 的 History 路由模式，防止刷新报 404
        try_files $uri $uri/ /index.html;
    }

    # （可选）也可以在这里配置反向代理，直接将 /api/v1 代理到后端，避免跨域
    # 我们之前的代码允许跨域且硬编码了 8080 端口，所以暂时不需要

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
